version: 2

jobs:
    build:
        docker:
            - image: circleci/python:3.6.4
              environment:
                    DEBUG: True
                    LOG_LEVEL: DEBUG
                    DATABASE_URL: postgres://root:@localhost:5432/circle_test
                    TEST_DATABASE_NAME: circle_test
                    SECRET_KEY: kableftkabloft
            - image: circleci/postgres:9.6.2
              environment:
                    POSTGRES_USER: root
                    POSTGRES_DB: circle_test
        steps:
            - checkout
            - run:
                command: |
                    sudo pip install -U -r requirements/test.txt
                    cd $(dirname $(find -name manage.py | head -1)) && python manage.py migrate
                    flake8 -v --ignore=E501 $(dirname $(find -name manage.py | head -1))
                    cd $(dirname $(find -name manage.py | head -1)) && pytest -x -vvv
