# Generated by Django 2.2.1 on 2019-05-01 18:58

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=utils.models.ulid_str_generator, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('end_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.CallEndRecord')),
                ('start_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.CallStartRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
